# -*- coding: utf-8 -*-
"""Atividade - Pensamento Computacional

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UaDZf56Eocy7MA-hyJePe6aH5B0ZoPzn

# Desafio 1
Cria um script Python que leia o nome de uma pessoa e mostra uma mensagem de boas-vindas de acordo com o valor digitado.
"""

nome = input('Digite o nome')
print('Seja Bem-vindo, {}!'.format(nome))

"""# Desafio 2
Cria um script Python que leia o dia. O mês e o ano de nascimento de uma pessoa e mostra uma mensagem com a data formatada.
"""

data = input('Qual é o dia do seu aniversario? ')
mes = input('Qual é o mês do seu aniversario? ')
ano = input('Qual é o ano do seu aniversario? ')
print('Você nasceu no dia {} do mês {} do ano de {}'.format(data, mes, ano))

date = input('Digite a data do seu nascimento: ddmmaaaa')
dia = date[0:2]
mes = date[2:4]
ano = date[4:8]
print('Você nasceu no dia {} do mês {} do ano de {}'.format(dia, mes, ano))

"""#Desafio 3
Crie um script Python que leia dois números e tenta mostrar a soma entre elas.
"""

X=2
Y=4
print(X+Y)

A=float(input('Digite A'))
B=float(input('Digite B'))
C=A+B
print(C)

"""# Desafio 4
- O algoritmo deve receber a idade do usuário e o ano atual. Retorne o ano de nascimento do usuário.

- Descrevendo o algoritmo:
       Ler o 2 número inteiro: idade, anoAtual
       Calcular o ano de nascimento: anoNascimento = anoAtual - idade
       Mostrar o valor do ano de nascimento (anoNascimento)
"""

idade = int(input('Digite a idade'))
anoAtual = int(input('Digite o ano atual'))
anoNascimento = anoAtual - idade
print('O ano de nascimento é {}'.format(anoNascimento))

