# -*- coding: utf-8 -*-
"""checkpoint1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDA2ZGze3rizXqNjLMc1h8FS5fiawLNd
"""

# Exercicio 1 - Checkpoint

# Conversor de Moedas - BRL para USD, EUR, ARS, GBP e JPY

valor_brl = float(input("Digite o valor em Reais (BRL): "))

# Conversões (usando taxas fixas)
print("\n==== Conversão de Moedas ====")
print(f"Valor em Real (BRL): R$ {valor_brl:.2f}")
print(f"Valor em Dólar (USD): {valor_brl / 5.10:.2f}")
print(f"Valor em Euro (EUR): {valor_brl / 5.45:.2f}")
print(f"Valor em Peso Argentino (ARS): {valor_brl / 0.020:.2f}")
print(f"Valor em Libra Esterlina (GBP): {valor_brl / 6.40:.2f}")
print(f"Valor em Iene (JPY): {valor_brl / 0.035:.2f}")

#Exercicio 2 - Checkpoint

# Entrada do usuário
num = int(input("Digite um número até 999: "))

# Cálculos
centena = (num // 100) * 100
dezena = ((num % 100) // 10) * 10
unidade = num % 10

# Exibição
print("\n==== Separação ====")
print(f"Centena = {centena}")
print(f"Dezena = {dezena}")
print(f"Unidade = {unidade}")

#Exercicio 3 - Checkpoint

anos = int(input("Digite a idade em anos: "))
meses = int(input("Digite os meses: "))
dias = int(input("Digite os dias: "))

# Cálculo (considerando 1 ano = 365 dias e 1 mês = 30 dias)
total_dias = (anos * 365) + (meses * 30) + dias


print("\n==== Resultado ====")
print(f"Idade em dias: {total_dias}")

#Exercicio 4 - Checkpoint

total_dias = int(input("Digite a idade em dias: "))

anos = total_dias // 365
resto = total_dias % 365
meses = resto // 30
dias = resto % 30

print("\n==== Resultado ====")
print(f"{anos} ano(s)")
print(f"{meses} mes(es)")
print(f"{dias} dia(s)")